<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSex1f8r\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSex1f8r/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSex1f8r.legacy');

    return;
}

if (!\class_exists(Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSex1f8r\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false);
}

return new \ContainerSex1f8r\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer([
    'container.build_hash' => 'Sex1f8r',
    'container.build_id' => 'c96ebb88',
    'container.build_time' => 1672725689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSex1f8r');
