<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ls4fqRWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ls4fqRW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ls4fqRW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customerProvider' => ['services', 'CustomerManagementFrameworkBundle\\CustomerProvider\\CustomerProviderInterface', 'getCustomerProviderInterfaceService', false],
        ], [
            'customerProvider' => 'CustomerManagementFrameworkBundle\\CustomerProvider\\CustomerProviderInterface',
        ]);
    }
}
