<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NHbyZrvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nHbyZrv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nHbyZrv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'object' => ['privates', '.errored..service_locator.nHbyZrv.Pimcore\\Model\\DataObject\\AbstractObject', NULL, 'Cannot autowire service ".service_locator.nHbyZrv": it references class "Pimcore\\Model\\DataObject\\AbstractObject" but no such service exists.'],
            'urlSlug' => ['privates', '.errored..service_locator.nHbyZrv.Pimcore\\Model\\DataObject\\Data\\UrlSlug', NULL, 'Cannot autowire service ".service_locator.nHbyZrv": it references class "Pimcore\\Model\\DataObject\\Data\\UrlSlug" but no such service exists.'],
        ], [
            'object' => 'Pimcore\\Model\\DataObject\\AbstractObject',
            'urlSlug' => 'Pimcore\\Model\\DataObject\\Data\\UrlSlug',
        ]);
    }
}
