<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AzbmqMzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.azbmqMz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.azbmqMz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'breadcrumbHelperService' => ['privates', 'App\\Website\\Navigation\\BreadcrumbHelperService', 'getBreadcrumbHelperServiceService', true],
            'factory' => ['services', 'pimcore_ecommerce.factory', 'getPimcoreEcommerce_FactoryService', true],
        ], [
            'breadcrumbHelperService' => 'App\\Website\\Navigation\\BreadcrumbHelperService',
            'factory' => '?',
        ]);
    }
}
