<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbstractObjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nHbyZrv.Pimcore\Model\DataObject\AbstractObject' shared service.
     *
     * @return \Pimcore\Model\DataObject\AbstractObject
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nHbyZrv": it references class "Pimcore\\Model\\DataObject\\AbstractObject" but no such service exists.');
    }
}
