<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminController4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController' shared autowired service.
     *
     * @return \Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/object-merger/src/Controller/AdminController.php';

        $container->services['Pimcore\\Bundle\\ObjectMergerBundle\\Controller\\AdminController'] = $instance = new \Pimcore\Bundle\ObjectMergerBundle\Controller\AdminController();

        $instance->setContainer(($container->privates['.service_locator.oafe0zm'] ?? $container->load('get_ServiceLocator_Oafe0zmService'))->withContext('Pimcore\\Bundle\\ObjectMergerBundle\\Controller\\AdminController', $container));

        return $instance;
    }
}
