<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBreadcrumbHelperServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Website\Navigation\BreadcrumbHelperService' shared autowired service.
     *
     * @return \App\Website\Navigation\BreadcrumbHelperService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Website/Navigation/BreadcrumbHelperService.php';

        $a = ($container->services['App\\Website\\LinkGenerator\\CategoryLinkGenerator'] ?? $container->getCategoryLinkGeneratorService());

        if (isset($container->privates['App\\Website\\Navigation\\BreadcrumbHelperService'])) {
            return $container->privates['App\\Website\\Navigation\\BreadcrumbHelperService'];
        }
        $b = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['App\\Website\\Navigation\\BreadcrumbHelperService'])) {
            return $container->privates['App\\Website\\Navigation\\BreadcrumbHelperService'];
        }

        return $container->privates['App\\Website\\Navigation\\BreadcrumbHelperService'] = new \App\Website\Navigation\BreadcrumbHelperService(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['Pimcore\\Twig\\Extension\\Templating\\Placeholder'] ?? $container->getPlaceholderService()), $a, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), $b);
    }
}
