<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuildSegmentsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.CustomerManagementFrameworkBundle\Command\BuildSegmentsCommand' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Command\BuildSegmentsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Command/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Command/BuildSegmentsCommand.php';

        $container->services['console.command.public_alias.CustomerManagementFrameworkBundle\\Command\\BuildSegmentsCommand'] = $instance = new \CustomerManagementFrameworkBundle\Command\BuildSegmentsCommand();

        $instance->setLogger(($container->services['monolog.logger.cmf'] ?? $container->load('getMonolog_Logger_CmfService')));

        return $instance;
    }
}
