<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_CustomerDuplicatesViewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.customer_duplicates_view' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\CustomerDuplicatesView\DefaultCustomerDuplicatesView
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/CustomerDuplicatesView/CustomerDuplicatesViewInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/CustomerDuplicatesView/DefaultCustomerDuplicatesView.php';

        return $container->services['cmf.customer_duplicates_view'] = new \CustomerManagementFrameworkBundle\CustomerDuplicatesView\DefaultCustomerDuplicatesView($container->parameters['pimcore_customer_management_framework.customer_duplicates_services.duplicates_view.listFields'], ($container->services['cmf.view_formatter'] ?? $container->getCmf_ViewFormatterService()));
    }
}
