<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupExportTmpDataTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\Maintenance\Tasks\CleanupExportTmpDataTask' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Maintenance\Tasks\CleanupExportTmpDataTask
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/TaskInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Maintenance/Tasks/CleanupExportTmpDataTask.php';

        return $container->services['CustomerManagementFrameworkBundle\\Maintenance\\Tasks\\CleanupExportTmpDataTask'] = new \CustomerManagementFrameworkBundle\Maintenance\Tasks\CleanupExportTmpDataTask(($container->services['CustomerManagementFrameworkBundle\\CustomerList\\ExporterManagerInterface'] ?? $container->getExporterManagerInterfaceService()));
    }
}
