<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_Rest_SegmentGroupsHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.rest.segment_groups_handler' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\RESTApi\SegmentGroupsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/HandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/AbstractHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/CrudHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/Traits/ResponseGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/Traits/ResourceUrlGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/RESTApi/SegmentGroupsHandler.php';

        $container->services['cmf.rest.segment_groups_handler'] = $instance = new \CustomerManagementFrameworkBundle\RESTApi\SegmentGroupsHandler(($container->services['Knp\\Component\\Pager\\PaginatorInterface'] ?? $container->getPaginatorInterfaceService()));

        $instance->setApiResourceRoute('customermanagementframework_rest_api_segmentgroups_readrecord');

        return $instance;
    }
}
