<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'CustomerManagementFrameworkBundle\GDPR\DataProvider\Customers' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\GDPR\DataProvider\Customers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/GDPR/DataProvider/DataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/GDPR/DataProvider/Elements.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/GDPR/DataProvider/DataObjects.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/GDPR/DataProvider/Customers.php';

        $a = ($container->services['cmf.activity_store'] ?? $container->getCmf_ActivityStoreService());

        if (isset($container->privates['CustomerManagementFrameworkBundle\\GDPR\\DataProvider\\Customers'])) {
            return $container->privates['CustomerManagementFrameworkBundle\\GDPR\\DataProvider\\Customers'];
        }

        return $container->privates['CustomerManagementFrameworkBundle\\GDPR\\DataProvider\\Customers'] = new \CustomerManagementFrameworkBundle\GDPR\DataProvider\Customers(($container->services['CustomerManagementFrameworkBundle\\CustomerProvider\\CustomerProviderInterface'] ?? $container->getCustomerProviderInterfaceService()), $a, $container->parameters['pimcore.gdpr-data-extrator.customers']);
    }
}
