<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Firewall_Authenticator_DemoFrontendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.firewall.authenticator.demo_frontend' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticatorManagerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/UserAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticatorManager.php';

        $a = ($container->privates['security.authenticator.form_login.demo_frontend'] ?? $container->load('getSecurity_Authenticator_FormLogin_DemoFrontendService'));

        if (isset($container->privates['debug.security.firewall.authenticator.demo_frontend'])) {
            return $container->privates['debug.security.firewall.authenticator.demo_frontend'];
        }
        $b = ($container->privates['security.authenticator.oauth.demo_frontend'] ?? $container->load('getSecurity_Authenticator_Oauth_DemoFrontendService'));

        if (isset($container->privates['debug.security.firewall.authenticator.demo_frontend'])) {
            return $container->privates['debug.security.firewall.authenticator.demo_frontend'];
        }

        return $container->privates['debug.security.firewall.authenticator.demo_frontend'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener(new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([0 => $a, 1 => $b, 2 => ($container->privates['security.authenticator.remember_me.demo_frontend'] ?? $container->load('getSecurity_Authenticator_RememberMe_DemoFrontendService'))], ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), ($container->privates['security.event_dispatcher.demo_frontend'] ?? $container->getSecurity_EventDispatcher_DemoFrontendService()), 'demo_frontend', ($container->services['monolog.logger.security'] ?? $container->getMonolog_Logger_SecurityService()), true, true, [])));
    }
}
