<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultSsoIdentityServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'CustomerManagementFrameworkBundle\Security\SsoIdentity\DefaultSsoIdentityService' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Security\SsoIdentity\DefaultSsoIdentityService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Security/SsoIdentity/SsoIdentityServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Security/SsoIdentity/DefaultSsoIdentityService.php';

        $container->privates['CustomerManagementFrameworkBundle\\Security\\SsoIdentity\\DefaultSsoIdentityService'] = $instance = new \CustomerManagementFrameworkBundle\Security\SsoIdentity\DefaultSsoIdentityService(($container->services['CustomerManagementFrameworkBundle\\CustomerProvider\\CustomerProviderInterface'] ?? $container->getCustomerProviderInterfaceService()));

        $instance->setLogger(($container->services['monolog.logger.cmf'] ?? $container->load('getMonolog_Logger_CmfService')));

        return $instance;
    }
}
