<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementSegmentsListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'CustomerManagementFrameworkBundle\Targeting\EventListener\ElementSegmentsListener' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Targeting\EventListener\ElementSegmentsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Targeting/EventListener/ElementSegmentsListener.php';

        $a = ($container->privates['CustomerManagementFrameworkBundle\\Targeting\\SegmentTracker'] ?? $container->load('getSegmentTrackerService'));

        if (isset($container->privates['CustomerManagementFrameworkBundle\\Targeting\\EventListener\\ElementSegmentsListener'])) {
            return $container->privates['CustomerManagementFrameworkBundle\\Targeting\\EventListener\\ElementSegmentsListener'];
        }

        return $container->privates['CustomerManagementFrameworkBundle\\Targeting\\EventListener\\ElementSegmentsListener'] = new \CustomerManagementFrameworkBundle\Targeting\EventListener\ElementSegmentsListener($container->parameters['pimcore_customer_management_framework.segment_assignment_classes.types'], ($container->services['Pimcore\\Http\\Request\\Resolver\\DocumentResolver'] ?? $container->getDocumentResolverService()), ($container->services['CustomerManagementFrameworkBundle\\SegmentManager\\SegmentManagerInterface'] ?? $container->getSegmentManagerInterfaceService()), $a);
    }
}
