<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindologicControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\EcommerceFrameworkBundle\Controller\FindologicController' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\Controller\FindologicController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/FrontendController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Controller/FindologicController.php';

        $container->services['Pimcore\\Bundle\\EcommerceFrameworkBundle\\Controller\\FindologicController'] = $instance = new \Pimcore\Bundle\EcommerceFrameworkBundle\Controller\FindologicController();

        $instance->setContainer(($container->privates['.service_locator.Z3eEsyj'] ?? $container->load('get_ServiceLocator_Z3eEsyjService'))->withContext('Pimcore\\Bundle\\EcommerceFrameworkBundle\\Controller\\FindologicController', $container));

        return $instance;
    }
}
