<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\CustomerView\Customer\Maintenance' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\CustomerView\Customer\Maintenance
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/CustomerView/Customer/Maintenance.php';

        return $container->services['CustomerManagementFrameworkBundle\\CustomerView\\Customer\\Maintenance'] = new \CustomerManagementFrameworkBundle\CustomerView\Customer\Maintenance();
    }
}
