<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sitemaps\NewsGenerator' shared autowired service.
     *
     * @return \App\Sitemaps\NewsGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/Element/AbstractElementGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Sitemaps/NewsGenerator.php';

        return $container->privates['App\\Sitemaps\\NewsGenerator'] = new \App\Sitemaps\NewsGenerator(($container->services['Pimcore\\Localization\\LocaleServiceInterface'] ?? $container->getLocaleServiceInterfaceService()), [], [0 => ($container->privates['App\\Sitemaps\\Processors\\AbsoluteURLProcessor'] ?? $container->load('getAbsoluteURLProcessorService'))]);
    }
}
