<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterQueueInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.16EjchC.CustomerManagementFrameworkBundle\Newsletter\Queue\NewsletterQueueInterface' shared service.
     *
     * @return \CustomerManagementFrameworkBundle\Newsletter\Queue\NewsletterQueueInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.16EjchC": it references interface "CustomerManagementFrameworkBundle\\Newsletter\\Queue\\NewsletterQueueInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
