<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderManagerLocatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\OrderManagerLocatorInterface' shared service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\OrderManagerLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/TenantAwareServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/CheckoutTenantAwareServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerLocator.php';

        return $container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\OrderManager\\OrderManagerLocatorInterface'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\OrderManagerLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['services', 'pimcore_ecommerce.order_manager.default', 'getPimcoreEcommerce_OrderManager_DefaultService', true],
        ], [
            'default' => '?',
        ]), ($container->services['pimcore_ecommerce.environment'] ?? $container->getPimcoreEcommerce_EnvironmentService()), false);
    }
}
