<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectPreviewControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\Controller\Preview\ObjectPreviewController' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Controller\Preview\ObjectPreviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/FrontendController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Controller/Preview/ObjectPreviewController.php';

        $container->services['CustomerManagementFrameworkBundle\\Controller\\Preview\\ObjectPreviewController'] = $instance = new \CustomerManagementFrameworkBundle\Controller\Preview\ObjectPreviewController();

        $instance->setContainer(($container->privates['.service_locator.Z3eEsyj'] ?? $container->load('get_ServiceLocator_Z3eEsyjService'))->withContext('CustomerManagementFrameworkBundle\\Controller\\Preview\\ObjectPreviewController', $container));

        return $instance;
    }
}
