<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectValueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/IndexService/Interpreter/InterpreterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Traits/OptionsResolverTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/IndexService/Interpreter/ObjectValue.php';

        return $container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\IndexService\\Interpreter\\ObjectValue'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue();
    }
}
