<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_CartManager_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore_ecommerce.cart_manager.default' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\MultiCartManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/MultiCartManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculatorFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculatorFactory.php';

        $a = ($container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\OrderManager\\OrderManagerLocatorInterface'] ?? $container->load('getOrderManagerLocatorInterfaceService'));

        if (isset($container->services['pimcore_ecommerce.cart_manager.default'])) {
            return $container->services['pimcore_ecommerce.cart_manager.default'];
        }

        return $container->services['pimcore_ecommerce.cart_manager.default'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\MultiCartManager(($container->services['pimcore_ecommerce.environment'] ?? $container->getPimcoreEcommerce_EnvironmentService()), new \Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartFactory(['cart_class_name' => 'Pimcore\\Bundle\\EcommerceFrameworkBundle\\CartManager\\Cart', 'guest_cart_class_name' => 'Pimcore\\Bundle\\EcommerceFrameworkBundle\\CartManager\\SessionCart']), new \Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartPriceCalculatorFactory(['Shipping' => ['class' => 'App\\Ecommerce\\Cart\\PriceModificator\\Shipping', 'options' => ['baseCharge' => '10', 'carCharge' => '200']]], ['class' => 'Pimcore\\Bundle\\EcommerceFrameworkBundle\\CartManager\\CartPriceCalculator']), $a, ($container->services['monolog.logger.pimcore_ecommerce'] ?? $container->load('getMonolog_Logger_PimcoreEcommerceService')));
    }
}
