<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_FilterService_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pimcore_ecommerce.filter_service.default' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterService.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterGroupHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/Input.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRange.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRangeSelection.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/Select.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectFromMultiSelect.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelect.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectFromMultiSelect.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectRelation.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectCategory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectRelation.php';

        $a = ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService());
        $b = ($container->services['pimcore.templating.engine.delegating'] ?? $container->getPimcore_Templating_Engine_DelegatingService());

        if (isset($container->privates['pimcore_ecommerce.filter_service.default'])) {
            return $container->privates['pimcore_ecommerce.filter_service.default'];
        }
        $c = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        return $container->privates['pimcore_ecommerce.filter_service.default'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterService(new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterGroupHelper(), ['FilterInputfield' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Input($a, $b, $c, 'product/filters/input.html.twig'), 'FilterNumberRange' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRange($a, $b, $c, 'product/filters/numberrange.html.twig'), 'FilterNumberRangeSelection' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRangeSelection($a, $b, $c, 'product/filters/numberrange_select.html.twig'), 'FilterSelect' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Select($a, $b, $c, 'product/filters/select.html.twig'), 'FilterSelectFromMultiSelect' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectFromMultiSelect($a, $b, $c, 'product/filters/select.html.twig'), 'FilterMultiSelect' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelect($a, $b, $c, 'product/filters/multi_select.html.twig'), 'FilterMultiSelectFromMultiSelect' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectFromMultiSelect($a, $b, $c, 'product/filters/multi_select.html.twig'), 'FilterMultiRelation' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectRelation($a, $b, $c, 'product/filters/multi_relation.html.twig'), 'FilterCategory' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectCategory($a, $b, $c, 'product/filters/select_category.html.twig'), 'FilterRelation' => new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectRelation($a, $b, $c, 'product/filters/object_relation.html.twig')]);
    }
}
