<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentAssignmentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\Controller\Admin\SegmentAssignmentController' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Controller\Admin\SegmentAssignmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin/SegmentAssignmentController.php';

        $container->services['CustomerManagementFrameworkBundle\\Controller\\Admin\\SegmentAssignmentController'] = $instance = new \CustomerManagementFrameworkBundle\Controller\Admin\SegmentAssignmentController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CustomerManagementFrameworkBundle\\SegmentAssignment\\SegmentAssigner\\SegmentAssignerInterface' => ['services', 'CustomerManagementFrameworkBundle\\SegmentAssignment\\SegmentAssigner\\SegmentAssignerInterface', 'getSegmentAssignerInterfaceService', true],
            'Pimcore\\Bundle\\AdminBundle\\Security\\User\\TokenStorageUserResolver' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\User\\TokenStorageUserResolver', 'getTokenStorageUserResolverService', false],
            'Pimcore\\Extension\\Bundle\\PimcoreBundleManager' => ['services', 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager', 'getPimcoreBundleManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'form.factory' => ['services', '.container.private.form.factory', 'get_Container_Private_Form_FactoryService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'message_bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'messenger.default_bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'pimcore.templating' => ['services', 'pimcore.templating.engine.delegating', 'getPimcore_Templating_Engine_DelegatingService', false],
            'pimcore_admin.serializer' => ['services', 'Pimcore\\Admin\\Serializer', 'getSerializer2Service', true],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['services', '.container.private.security.authorization_checker', 'get_Container_Private_Security_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['services', '.container.private.security.csrf.token_manager', 'get_Container_Private_Security_Csrf_TokenManagerService', true],
            'security.token_storage' => ['services', '.container.private.security.token_storage', 'get_Container_Private_Security_TokenStorageService', false],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'session' => ['privates', '.session.deprecated', 'get_Session_DeprecatedService', true],
            'translator' => ['services', 'Symfony\\Contracts\\Translation\\TranslatorInterface', 'getTranslatorInterfaceService', false],
            'twig' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', false],
        ], [
            'CustomerManagementFrameworkBundle\\SegmentAssignment\\SegmentAssigner\\SegmentAssignerInterface' => 'CustomerManagementFrameworkBundle\\SegmentAssignment\\SegmentAssigner\\SegmentAssignerInterface',
            'Pimcore\\Bundle\\AdminBundle\\Security\\User\\TokenStorageUserResolver' => 'Pimcore\\Bundle\\AdminBundle\\Security\\User\\TokenStorageUserResolver',
            'Pimcore\\Extension\\Bundle\\PimcoreBundleManager' => 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager',
            'doctrine' => '?',
            'form.factory' => '?',
            'http_kernel' => '?',
            'message_bus' => '?',
            'messenger.default_bus' => '?',
            'parameter_bag' => '?',
            'pimcore.templating' => '?',
            'pimcore_admin.serializer' => 'Pimcore\\Admin\\Serializer',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'session' => '.session.deprecated',
            'translator' => '?',
            'twig' => '?',
        ]))->withContext('CustomerManagementFrameworkBundle\\Controller\\Admin\\SegmentAssignmentController', $container));

        return $instance;
    }
}
