<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_DemoFrontendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.context.demo_frontend' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallContext.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Util/TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/ExceptionListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/LogoutListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        $a = ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService());
        $b = ($container->privates['security.http_utils'] ?? $container->getSecurity_HttpUtilsService());
        $c = ($container->privates['security.authenticator.form_login.demo_frontend'] ?? $container->load('getSecurity_Authenticator_FormLogin_DemoFrontendService'));

        if (isset($container->privates['security.firewall.map.context.demo_frontend'])) {
            return $container->privates['security.firewall.map.context.demo_frontend'];
        }

        return $container->privates['security.firewall.map.context.demo_frontend'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.1'] ?? $container->getSecurity_ContextListener_1Service());
            yield 2 => ($container->privates['debug.security.firewall.authenticator.demo_frontend'] ?? $container->load('getDebug_Security_Firewall_Authenticator_DemoFrontendService'));
            yield 3 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 4), new \Symfony\Component\Security\Http\Firewall\ExceptionListener($a, ($container->privates['scheb_two_factor.security.authentication.trust_resolver'] ?? $container->getSchebTwoFactor_Security_Authentication_TrustResolverService()), $b, 'demo_frontend', $c, NULL, NULL, ($container->services['monolog.logger.security'] ?? $container->getMonolog_Logger_SecurityService()), false), new \Symfony\Component\Security\Http\Firewall\LogoutListener($a, $b, ($container->privates['security.event_dispatcher.demo_frontend'] ?? $container->getSecurity_EventDispatcher_DemoFrontendService()), ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'account-logout']), new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('demo_frontend', 'security.user_checker', NULL, true, false, 'cmf.security.user_provider.oauth', 'demo_frontend', 'security.authenticator.form_login.demo_frontend', NULL, NULL, [0 => 'form_login', 1 => 'oauth', 2 => 'remember_me'], NULL));
    }
}
