<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentExtractorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\SegmentManager\SegmentExtractor\SegmentExtractorInterface' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\SegmentManager\SegmentExtractor\DefaultSegmentExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/SegmentManager/SegmentExtractor/SegmentExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/SegmentManager/SegmentExtractor/DefaultSegmentExtractor.php';

        return $container->services['CustomerManagementFrameworkBundle\\SegmentManager\\SegmentExtractor\\SegmentExtractorInterface'] = new \CustomerManagementFrameworkBundle\SegmentManager\SegmentExtractor\DefaultSegmentExtractor();
    }
}
