<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getService2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\DataHubBundle\GraphQL\Service' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataHubBundle\GraphQL\Service
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/Service.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/Traits/ServiceTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/AbstractFieldHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/AssetFieldHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DocumentFieldHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/Type.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/HasFieldsType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/TypeWithFields.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/OutputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/CompositeType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/NullableType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/NamedType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/ImplementingType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/AssetType/AssetMetadataItem.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/InputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/AssetType/AssetInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/General/FolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/AssetType/AssetFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Type/Definition/UnionType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/AssetType/AssetTreeType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/ElementDescriptorInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/GeopointInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/ObjectTreeType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/ObjectFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/HotspotType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/AbstractRelationsType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/HrefType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/QuantityValueType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/InputQuantityValueType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/UrlSlugType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/VideoType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/VideoTypeDataType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/QuantityValueInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/InputType/AbstractRelationInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/InputType/ImageInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/DocumentType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/AbstractDocumentType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/PageSnippetType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/PageType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/DocumentElementType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/LinkType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/EmailType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/HardlinkType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/General/AnyDocumentTargetType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/SnippetType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/DocumentTreeType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/DocumentFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/DocumentType/DocumentLinkInputType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/ClassificationstoreType/Group.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/ClassificationstoreType/Feature.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/ElementPropertyType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/HotspotMetadataType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/AssetType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/DocumentType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/AssetFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/DocumentFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/ObjectFolderType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/DataObjectType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/ObjectsType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/CheckboxType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/TextareaType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/TextType.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/GraphQL/PropertyType/SelectType.php';

        $a = new \Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\AssetFieldHelper();

        $b = new \Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DocumentFieldHelper();

        $c = new \Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper();

        $container->services['Pimcore\\Bundle\\DataHubBundle\\GraphQL\\Service'] = $instance = new \Pimcore\Bundle\DataHubBundle\GraphQL\Service($a, $b, $c, ($container->services['Pimcore\\Localization\\LocaleServiceInterface'] ?? $container->getLocaleServiceInterfaceService()), ($container->services['pimcore.model.factory'] ?? $container->getPimcore_Model_FactoryService()), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $container->getTranslatorInterfaceService()), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typegenerator_dataobjectquerydatatype_advancedManyToManyObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_objectsMetadata', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeObjectsMetadataService', true],
            'typegenerator_dataobjectquerydatatype_advancedManyToManyRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multihrefMetadata', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultihrefMetadataService', true],
            'typegenerator_dataobjectquerydatatype_block' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_block', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeBlockService', true],
            'typegenerator_dataobjectquerydatatype_booleanSelect' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_dataobjectquerydatatype_calculatedValue' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_calculatedvalue', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeCalculatedvalueService', true],
            'typegenerator_dataobjectquerydatatype_checkbox' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_dataobjectquerydatatype_classificationstore' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_classificationstore', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeClassificationstoreService', true],
            'typegenerator_dataobjectquerydatatype_country' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeSelectService', true],
            'typegenerator_dataobjectquerydatatype_countrymultiselect' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultiselectService', true],
            'typegenerator_dataobjectquerydatatype_date' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_date', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeDateService', true],
            'typegenerator_dataobjectquerydatatype_datetime' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_datetime', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeDatetimeService', true],
            'typegenerator_dataobjectquerydatatype_email' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_email', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeEmailService', true],
            'typegenerator_dataobjectquerydatatype_externalImage' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeInputService', true],
            'typegenerator_dataobjectquerydatatype_fieldcollections' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_fieldcollections', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeFieldcollectionsService', true],
            'typegenerator_dataobjectquerydatatype_firstname' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_firstname', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeFirstnameService', true],
            'typegenerator_dataobjectquerydatatype_gender' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeSelectService', true],
            'typegenerator_dataobjectquerydatatype_geobounds' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_geobounds', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeGeoboundsService', true],
            'typegenerator_dataobjectquerydatatype_geopoint' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_geopoint', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeGeopointService', true],
            'typegenerator_dataobjectquerydatatype_geopolygon' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_geopolygon', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeGeopolygonService', true],
            'typegenerator_dataobjectquerydatatype_hotspotimage' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_hotspotimage', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeHotspotimageService', true],
            'typegenerator_dataobjectquerydatatype_href' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_href', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeHrefService', true],
            'typegenerator_dataobjectquerydatatype_image' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_image', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeImageService', true],
            'typegenerator_dataobjectquerydatatype_imageGallery' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_imageGallery', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeImageGalleryService', true],
            'typegenerator_dataobjectquerydatatype_input' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeInputService', true],
            'typegenerator_dataobjectquerydatatype_inputQuantityValue' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_inputquantityvalue', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeInputquantityvalueService', true],
            'typegenerator_dataobjectquerydatatype_language' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeSelectService', true],
            'typegenerator_dataobjectquerydatatype_languagemultiselect' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultiselectService', true],
            'typegenerator_dataobjectquerydatatype_lastname' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_lastname', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeLastnameService', true],
            'typegenerator_dataobjectquerydatatype_link' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_link', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeLinkService', true],
            'typegenerator_dataobjectquerydatatype_manyToManyObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_objects', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeObjectsService', true],
            'typegenerator_dataobjectquerydatatype_manyToManyRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multihref', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultihrefService', true],
            'typegenerator_dataobjectquerydatatype_manyToOneRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_href', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeHrefService', true],
            'typegenerator_dataobjectquerydatatype_multihref' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multihref', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultihrefService', true],
            'typegenerator_dataobjectquerydatatype_multihrefMetadata' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multihrefMetadata', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultihrefMetadataService', true],
            'typegenerator_dataobjectquerydatatype_multiselect' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeMultiselectService', true],
            'typegenerator_dataobjectquerydatatype_newsletterActive' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_dataobjectquerydatatype_newsletterConfirmed' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_dataobjectquerydatatype_numeric' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_numeric', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeNumericService', true],
            'typegenerator_dataobjectquerydatatype_quantityValue' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_quantityvalue', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeQuantityvalueService', true],
            'typegenerator_dataobjectquerydatatype_reverseManyToManyObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_reverseManyToManyObjectRelation', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeReverseManyToManyObjectRelationService', true],
            'typegenerator_dataobjectquerydatatype_reverseObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_reverseManyToManyObjectRelation', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeReverseManyToManyObjectRelationService', true],
            'typegenerator_dataobjectquerydatatype_rgbaColor' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeInputService', true],
            'typegenerator_dataobjectquerydatatype_select' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeSelectService', true],
            'typegenerator_dataobjectquerydatatype_slider' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_slider', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeSliderService', true],
            'typegenerator_dataobjectquerydatatype_structuredTable' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_structuredTable', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeStructuredTableService', true],
            'typegenerator_dataobjectquerydatatype_table' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_table', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeTableService', true],
            'typegenerator_dataobjectquerydatatype_textarea' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_textarea', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeTextareaService', true],
            'typegenerator_dataobjectquerydatatype_time' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeInputService', true],
            'typegenerator_dataobjectquerydatatype_urlSlug' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_urlSlug', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeUrlSlugService', true],
            'typegenerator_dataobjectquerydatatype_video' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_video', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeVideoService', true],
            'typegenerator_dataobjectquerydatatype_wysiwyg' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_wysiwyg', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorDatatypeWysiwygService', true],
            'typegenerator_queryoperator_alias' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_alias', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorAliasService', true],
            'typegenerator_queryoperator_concatenator' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_concatenator', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorConcatenatorService', true],
            'typegenerator_queryoperator_dateformatter' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_dateformatter', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorDateformatterService', true],
            'typegenerator_queryoperator_elementcounter' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_elementcounter', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorElementcounterService', true],
            'typegenerator_queryoperator_merge' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_merge', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorMergeService', true],
            'typegenerator_queryoperator_substring' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_substring', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorSubstringService', true],
            'typegenerator_queryoperator_text' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_text', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorTextService', true],
            'typegenerator_queryoperator_thumbnail' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_thumbnail', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorThumbnailService', true],
            'typegenerator_queryoperator_thumbnailhtml' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_thumbnailhtml', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorThumbnailhtmlService', true],
            'typegenerator_queryoperator_translatevalue' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_translatevalue', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorTranslatevalueService', true],
            'typegenerator_queryoperator_trimmer' => ['privates', 'pimcore.datahub.graphql.dataobjectquerytypegenerator_operator_trimmer', 'getPimcore_Datahub_Graphql_DataobjectquerytypegeneratorOperatorTrimmerService', true],
        ], [
            'typegenerator_dataobjectquerydatatype_advancedManyToManyObjectRelation' => '?',
            'typegenerator_dataobjectquerydatatype_advancedManyToManyRelation' => '?',
            'typegenerator_dataobjectquerydatatype_block' => '?',
            'typegenerator_dataobjectquerydatatype_booleanSelect' => '?',
            'typegenerator_dataobjectquerydatatype_calculatedValue' => '?',
            'typegenerator_dataobjectquerydatatype_checkbox' => '?',
            'typegenerator_dataobjectquerydatatype_classificationstore' => '?',
            'typegenerator_dataobjectquerydatatype_country' => '?',
            'typegenerator_dataobjectquerydatatype_countrymultiselect' => '?',
            'typegenerator_dataobjectquerydatatype_date' => '?',
            'typegenerator_dataobjectquerydatatype_datetime' => '?',
            'typegenerator_dataobjectquerydatatype_email' => '?',
            'typegenerator_dataobjectquerydatatype_externalImage' => '?',
            'typegenerator_dataobjectquerydatatype_fieldcollections' => '?',
            'typegenerator_dataobjectquerydatatype_firstname' => '?',
            'typegenerator_dataobjectquerydatatype_gender' => '?',
            'typegenerator_dataobjectquerydatatype_geobounds' => '?',
            'typegenerator_dataobjectquerydatatype_geopoint' => '?',
            'typegenerator_dataobjectquerydatatype_geopolygon' => '?',
            'typegenerator_dataobjectquerydatatype_hotspotimage' => '?',
            'typegenerator_dataobjectquerydatatype_href' => '?',
            'typegenerator_dataobjectquerydatatype_image' => '?',
            'typegenerator_dataobjectquerydatatype_imageGallery' => '?',
            'typegenerator_dataobjectquerydatatype_input' => '?',
            'typegenerator_dataobjectquerydatatype_inputQuantityValue' => '?',
            'typegenerator_dataobjectquerydatatype_language' => '?',
            'typegenerator_dataobjectquerydatatype_languagemultiselect' => '?',
            'typegenerator_dataobjectquerydatatype_lastname' => '?',
            'typegenerator_dataobjectquerydatatype_link' => '?',
            'typegenerator_dataobjectquerydatatype_manyToManyObjectRelation' => '?',
            'typegenerator_dataobjectquerydatatype_manyToManyRelation' => '?',
            'typegenerator_dataobjectquerydatatype_manyToOneRelation' => '?',
            'typegenerator_dataobjectquerydatatype_multihref' => '?',
            'typegenerator_dataobjectquerydatatype_multihrefMetadata' => '?',
            'typegenerator_dataobjectquerydatatype_multiselect' => '?',
            'typegenerator_dataobjectquerydatatype_newsletterActive' => '?',
            'typegenerator_dataobjectquerydatatype_newsletterConfirmed' => '?',
            'typegenerator_dataobjectquerydatatype_numeric' => '?',
            'typegenerator_dataobjectquerydatatype_quantityValue' => '?',
            'typegenerator_dataobjectquerydatatype_reverseManyToManyObjectRelation' => '?',
            'typegenerator_dataobjectquerydatatype_reverseObjectRelation' => '?',
            'typegenerator_dataobjectquerydatatype_rgbaColor' => '?',
            'typegenerator_dataobjectquerydatatype_select' => '?',
            'typegenerator_dataobjectquerydatatype_slider' => '?',
            'typegenerator_dataobjectquerydatatype_structuredTable' => '?',
            'typegenerator_dataobjectquerydatatype_table' => '?',
            'typegenerator_dataobjectquerydatatype_textarea' => '?',
            'typegenerator_dataobjectquerydatatype_time' => '?',
            'typegenerator_dataobjectquerydatatype_urlSlug' => '?',
            'typegenerator_dataobjectquerydatatype_video' => '?',
            'typegenerator_dataobjectquerydatatype_wysiwyg' => '?',
            'typegenerator_queryoperator_alias' => '?',
            'typegenerator_queryoperator_concatenator' => '?',
            'typegenerator_queryoperator_dateformatter' => '?',
            'typegenerator_queryoperator_elementcounter' => '?',
            'typegenerator_queryoperator_merge' => '?',
            'typegenerator_queryoperator_substring' => '?',
            'typegenerator_queryoperator_text' => '?',
            'typegenerator_queryoperator_thumbnail' => '?',
            'typegenerator_queryoperator_thumbnailhtml' => '?',
            'typegenerator_queryoperator_translatevalue' => '?',
            'typegenerator_queryoperator_trimmer' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alias' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.alias', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_AliasService', true],
            'concatenator' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.concatenator', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_ConcatenatorService', true],
            'dateformatter' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.dateformatter', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_DateformatterService', true],
            'elementcounter' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.elementcounter', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_ElementcounterService', true],
            'merge' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.merge', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_MergeService', true],
            'substring' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.substring', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_SubstringService', true],
            'text' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.text', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_TextService', true],
            'thumbnail' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.thumbnail', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_ThumbnailService', true],
            'thumbnailhtml' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.thumbnailhtml', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_ThumbnailhtmlService', true],
            'translatevalue' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.translatevalue', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_TranslatevalueService', true],
            'trimmer' => ['privates', 'pimcore.datahub.graphql.dataobjectqueryoperator.factory.trimmer', 'getPimcore_Datahub_Graphql_Dataobjectqueryoperator_Factory_TrimmerService', true],
        ], [
            'alias' => '?',
            'concatenator' => '?',
            'dateformatter' => '?',
            'elementcounter' => '?',
            'merge' => '?',
            'substring' => '?',
            'text' => '?',
            'thumbnail' => '?',
            'thumbnailhtml' => '?',
            'translatevalue' => '?',
            'trimmer' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typegenerator_dataobjectmutationdatatype_advancedManyToManyObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_advancedManyToManyObjectRelation', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeAdvancedManyToManyObjectRelationService', true],
            'typegenerator_dataobjectmutationdatatype_advancedManyToManyRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_advancedManyToManyRelation', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeAdvancedManyToManyRelationService', true],
            'typegenerator_dataobjectmutationdatatype_booleanSelect' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_booleanSelect', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeBooleanSelectService', true],
            'typegenerator_dataobjectmutationdatatype_checkbox' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeCheckboxService', true],
            'typegenerator_dataobjectmutationdatatype_country' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_country', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeCountryService', true],
            'typegenerator_dataobjectmutationdatatype_countrymultiselect' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_countrymultiselect', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeCountrymultiselectService', true],
            'typegenerator_dataobjectmutationdatatype_date' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_date', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeDateService', true],
            'typegenerator_dataobjectmutationdatatype_datetime' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_datetime', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeDatetimeService', true],
            'typegenerator_dataobjectmutationdatatype_email' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_email', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeEmailService', true],
            'typegenerator_dataobjectmutationdatatype_externalImage' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_externalImage', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeExternalImageService', true],
            'typegenerator_dataobjectmutationdatatype_fieldcollections' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_fieldcollections', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeFieldcollectionsService', true],
            'typegenerator_dataobjectmutationdatatype_firstname' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_firstname', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeFirstnameService', true],
            'typegenerator_dataobjectmutationdatatype_gender' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_gender', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeGenderService', true],
            'typegenerator_dataobjectmutationdatatype_geopoint' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_geopoint', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeGeopointService', true],
            'typegenerator_dataobjectmutationdatatype_image' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_image', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeImageService', true],
            'typegenerator_dataobjectmutationdatatype_input' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeInputService', true],
            'typegenerator_dataobjectmutationdatatype_language' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_language', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeLanguageService', true],
            'typegenerator_dataobjectmutationdatatype_lastname' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_lastname', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeLastnameService', true],
            'typegenerator_dataobjectmutationdatatype_manyToManyObjectRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_manyToManyObjectRelation', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeManyToManyObjectRelationService', true],
            'typegenerator_dataobjectmutationdatatype_manyToManyRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_manyToManyRelation', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeManyToManyRelationService', true],
            'typegenerator_dataobjectmutationdatatype_manyToOneRelation' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_manyToOneRelation', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeManyToOneRelationService', true],
            'typegenerator_dataobjectmutationdatatype_multiselect' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeMultiselectService', true],
            'typegenerator_dataobjectmutationdatatype_newsletterActive' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_newsletterActive', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeNewsletterActiveService', true],
            'typegenerator_dataobjectmutationdatatype_newsletterConfirmed' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_newsletterConfirmed', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeNewsletterConfirmedService', true],
            'typegenerator_dataobjectmutationdatatype_numeric' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_numeric', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeNumericService', true],
            'typegenerator_dataobjectmutationdatatype_quantityValue' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_quantityValue', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeQuantityValueService', true],
            'typegenerator_dataobjectmutationdatatype_select' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeSelectService', true],
            'typegenerator_dataobjectmutationdatatype_slider' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_slider', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeSliderService', true],
            'typegenerator_dataobjectmutationdatatype_textarea' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_textarea', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeTextareaService', true],
            'typegenerator_dataobjectmutationdatatype_time' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_time', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeTimeService', true],
            'typegenerator_dataobjectmutationdatatype_wysiwyg' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_wysiwyg', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorDatatypeWysiwygService', true],
            'typegenerator_dataobjectmutationoperator_ifempty' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_operator_ifempty', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorOperatorIfemptyService', true],
            'typegenerator_dataobjectmutationoperator_localecollector' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_operator_localecollector', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorOperatorLocalecollectorService', true],
            'typegenerator_dataobjectmutationoperator_localeswitcher' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationtypegenerator_operator_localeswitcher', 'getPimcore_Datahub_Graphql_DataobjectmutationtypegeneratorOperatorLocaleswitcherService', true],
        ], [
            'typegenerator_dataobjectmutationdatatype_advancedManyToManyObjectRelation' => '?',
            'typegenerator_dataobjectmutationdatatype_advancedManyToManyRelation' => '?',
            'typegenerator_dataobjectmutationdatatype_booleanSelect' => '?',
            'typegenerator_dataobjectmutationdatatype_checkbox' => '?',
            'typegenerator_dataobjectmutationdatatype_country' => '?',
            'typegenerator_dataobjectmutationdatatype_countrymultiselect' => '?',
            'typegenerator_dataobjectmutationdatatype_date' => '?',
            'typegenerator_dataobjectmutationdatatype_datetime' => '?',
            'typegenerator_dataobjectmutationdatatype_email' => '?',
            'typegenerator_dataobjectmutationdatatype_externalImage' => '?',
            'typegenerator_dataobjectmutationdatatype_fieldcollections' => '?',
            'typegenerator_dataobjectmutationdatatype_firstname' => '?',
            'typegenerator_dataobjectmutationdatatype_gender' => '?',
            'typegenerator_dataobjectmutationdatatype_geopoint' => '?',
            'typegenerator_dataobjectmutationdatatype_image' => '?',
            'typegenerator_dataobjectmutationdatatype_input' => '?',
            'typegenerator_dataobjectmutationdatatype_language' => '?',
            'typegenerator_dataobjectmutationdatatype_lastname' => '?',
            'typegenerator_dataobjectmutationdatatype_manyToManyObjectRelation' => '?',
            'typegenerator_dataobjectmutationdatatype_manyToManyRelation' => '?',
            'typegenerator_dataobjectmutationdatatype_manyToOneRelation' => '?',
            'typegenerator_dataobjectmutationdatatype_multiselect' => '?',
            'typegenerator_dataobjectmutationdatatype_newsletterActive' => '?',
            'typegenerator_dataobjectmutationdatatype_newsletterConfirmed' => '?',
            'typegenerator_dataobjectmutationdatatype_numeric' => '?',
            'typegenerator_dataobjectmutationdatatype_quantityValue' => '?',
            'typegenerator_dataobjectmutationdatatype_select' => '?',
            'typegenerator_dataobjectmutationdatatype_slider' => '?',
            'typegenerator_dataobjectmutationdatatype_textarea' => '?',
            'typegenerator_dataobjectmutationdatatype_time' => '?',
            'typegenerator_dataobjectmutationdatatype_wysiwyg' => '?',
            'typegenerator_dataobjectmutationoperator_ifempty' => '?',
            'typegenerator_dataobjectmutationoperator_localecollector' => '?',
            'typegenerator_dataobjectmutationoperator_localeswitcher' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ifempty' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationoperator.factory.ifempty', 'getPimcore_Datahub_Graphql_Dataobjectmutationoperator_Factory_IfemptyService', true],
            'localecollector' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationoperator.factory.localecollector', 'getPimcore_Datahub_Graphql_Dataobjectmutationoperator_Factory_LocalecollectorService', true],
            'localeswitcher' => ['privates', 'pimcore.datahub.graphql.dataobjectmutationoperator.factory.localeswitcher', 'getPimcore_Datahub_Graphql_Dataobjectmutationoperator_Factory_LocaleswitcherService', true],
        ], [
            'ifempty' => '?',
            'localecollector' => '?',
            'localeswitcher' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typegenerator_documentelementquerydatatype_areablock' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_areablock', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeAreablockService', true],
            'typegenerator_documentelementquerydatatype_block' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_block', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeBlockService', true],
            'typegenerator_documentelementquerydatatype_checkbox' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_documentelementquerydatatype_date' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_date', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeDateService', true],
            'typegenerator_documentelementquerydatatype_embed' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_embed', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeEmbedService', true],
            'typegenerator_documentelementquerydatatype_image' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_image', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeImageService', true],
            'typegenerator_documentelementquerydatatype_input' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeInputService', true],
            'typegenerator_documentelementquerydatatype_link' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_link', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeLinkService', true],
            'typegenerator_documentelementquerydatatype_multiselect' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeMultiselectService', true],
            'typegenerator_documentelementquerydatatype_numeric' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_numeric', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeNumericService', true],
            'typegenerator_documentelementquerydatatype_pdf' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_pdf', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypePdfService', true],
            'typegenerator_documentelementquerydatatype_relation' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_relation', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeRelationService', true],
            'typegenerator_documentelementquerydatatype_relations' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_relations', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeRelationsService', true],
            'typegenerator_documentelementquerydatatype_scheduledblock' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_scheduledblock', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeScheduledblockService', true],
            'typegenerator_documentelementquerydatatype_select' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeSelectService', true],
            'typegenerator_documentelementquerydatatype_table' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_table', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeTableService', true],
            'typegenerator_documentelementquerydatatype_textarea' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_textarea', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeTextareaService', true],
            'typegenerator_documentelementquerydatatype_video' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_video', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeVideoService', true],
            'typegenerator_documentelementquerydatatype_wysiwyg' => ['privates', 'pimcore.datahub.graphql.documentelementquerytypegenerator_datatype_wysiwyg', 'getPimcore_Datahub_Graphql_DocumentelementquerytypegeneratorDatatypeWysiwygService', true],
        ], [
            'typegenerator_documentelementquerydatatype_areablock' => '?',
            'typegenerator_documentelementquerydatatype_block' => '?',
            'typegenerator_documentelementquerydatatype_checkbox' => '?',
            'typegenerator_documentelementquerydatatype_date' => '?',
            'typegenerator_documentelementquerydatatype_embed' => '?',
            'typegenerator_documentelementquerydatatype_image' => '?',
            'typegenerator_documentelementquerydatatype_input' => '?',
            'typegenerator_documentelementquerydatatype_link' => '?',
            'typegenerator_documentelementquerydatatype_multiselect' => '?',
            'typegenerator_documentelementquerydatatype_numeric' => '?',
            'typegenerator_documentelementquerydatatype_pdf' => '?',
            'typegenerator_documentelementquerydatatype_relation' => '?',
            'typegenerator_documentelementquerydatatype_relations' => '?',
            'typegenerator_documentelementquerydatatype_scheduledblock' => '?',
            'typegenerator_documentelementquerydatatype_select' => '?',
            'typegenerator_documentelementquerydatatype_table' => '?',
            'typegenerator_documentelementquerydatatype_textarea' => '?',
            'typegenerator_documentelementquerydatatype_video' => '?',
            'typegenerator_documentelementquerydatatype_wysiwyg' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typegenerator_documentelementmutationdatatype_areablock' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_areablock', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeAreablockService', true],
            'typegenerator_documentelementmutationdatatype_block' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_block', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeBlockService', true],
            'typegenerator_documentelementmutationdatatype_embed' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_embed', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeEmbedService', true],
            'typegenerator_documentelementmutationdatatype_image' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_image', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeImageService', true],
            'typegenerator_documentelementmutationdatatype_input' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeInputService', true],
            'typegenerator_documentelementmutationdatatype_multiselect' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeMultiselectService', true],
            'typegenerator_documentelementmutationdatatype_scheduledblock' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_scheduledblock', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeScheduledblockService', true],
            'typegenerator_documentelementmutationdatatype_select' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeSelectService', true],
            'typegenerator_documentelementmutationdatatype_wysiwyg' => ['privates', 'pimcore.datahub.graphql.documentelementmutationtypegenerator_datatype_wysiwyg', 'getPimcore_Datahub_Graphql_DocumentelementmutationtypegeneratorDatatypeWysiwygService', true],
        ], [
            'typegenerator_documentelementmutationdatatype_areablock' => '?',
            'typegenerator_documentelementmutationdatatype_block' => '?',
            'typegenerator_documentelementmutationdatatype_embed' => '?',
            'typegenerator_documentelementmutationdatatype_image' => '?',
            'typegenerator_documentelementmutationdatatype_input' => '?',
            'typegenerator_documentelementmutationdatatype_multiselect' => '?',
            'typegenerator_documentelementmutationdatatype_scheduledblock' => '?',
            'typegenerator_documentelementmutationdatatype_select' => '?',
            'typegenerator_documentelementmutationdatatype_wysiwyg' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anytarget' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.anytargettype', 'getPimcore_Datahub_Graphql_Generaltype_Factory_AnytargettypeService', true],
            'asset_tree' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.asset_tree', 'getPimcore_Datahub_Graphql_Generaltype_Factory_AssetTreeService', true],
            'document_translation' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.document_translation', 'getPimcore_Datahub_Graphql_Generaltype_Factory_DocumentTranslationService', true],
            'document_tree' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.document_tree', 'getPimcore_Datahub_Graphql_Generaltype_Factory_DocumentTreeService', true],
            'element_property' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.element_property_property', 'getPimcore_Datahub_Graphql_Generaltype_Factory_ElementPropertyPropertyService', true],
            'element_tag' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.element_tag', 'getPimcore_Datahub_Graphql_Generaltype_Factory_ElementTagService', true],
            'hotspot_metadata' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.hotspot_metadata', 'getPimcore_Datahub_Graphql_Generaltype_Factory_HotspotMetadataService', true],
            'hotspothotspot' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.hotspothotspottype', 'getPimcore_Datahub_Graphql_Generaltype_Factory_HotspothotspottypeService', true],
            'hotspotmarker' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.hotspotmarkertype', 'getPimcore_Datahub_Graphql_Generaltype_Factory_HotspotmarkertypeService', true],
            'object_tree' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.object_tree', 'getPimcore_Datahub_Graphql_Generaltype_Factory_ObjectTreeService', true],
        ], [
            'anytarget' => '?',
            'asset_tree' => '?',
            'document_translation' => '?',
            'document_tree' => '?',
            'element_property' => '?',
            'element_tag' => '?',
            'hotspot_metadata' => '?',
            'hotspothotspot' => '?',
            'hotspotmarker' => '?',
            'object_tree' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asset' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.asset', 'getPimcore_Datahub_Graphql_Generaltype_Factory_AssetService', true],
            'asset_metadataitem' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.asset_metadataitem', 'getPimcore_Datahub_Graphql_Generaltype_Factory_AssetMetadataitemService', true],
            'video' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.video', 'getPimcore_Datahub_Graphql_Generaltype_Factory_VideoService', true],
        ], [
            'asset' => '?',
            'asset_metadataitem' => '?',
            'video' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typegenerator_csfeaturequerydatatype_booleanSelect' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_booleanSelect', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeBooleanSelectService', true],
            'typegenerator_csfeaturequerydatatype_calculatedValue' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_calculatedValue', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeCalculatedValueService', true],
            'typegenerator_csfeaturequerydatatype_checkbox' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_checkbox', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeCheckboxService', true],
            'typegenerator_csfeaturequerydatatype_country' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_country', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeCountryService', true],
            'typegenerator_csfeaturequerydatatype_countrymultiselect' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_countrymultiselect', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeCountrymultiselectService', true],
            'typegenerator_csfeaturequerydatatype_date' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_date', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeDateService', true],
            'typegenerator_csfeaturequerydatatype_datetime' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_datetime', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeDatetimeService', true],
            'typegenerator_csfeaturequerydatatype_input' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_input', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeInputService', true],
            'typegenerator_csfeaturequerydatatype_inputQuantityValue' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_inputQuantityValue', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeInputQuantityValueService', true],
            'typegenerator_csfeaturequerydatatype_language' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_language', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeLanguageService', true],
            'typegenerator_csfeaturequerydatatype_languagemultiselect' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_languagemultiselect', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeLanguagemultiselectService', true],
            'typegenerator_csfeaturequerydatatype_multiselect' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_multiselect', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeMultiselectService', true],
            'typegenerator_csfeaturequerydatatype_numeric' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_numeric', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeNumericService', true],
            'typegenerator_csfeaturequerydatatype_quantityValue' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_quantityValue', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeQuantityValueService', true],
            'typegenerator_csfeaturequerydatatype_rgbaColor' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_rgbaColor', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeRgbaColorService', true],
            'typegenerator_csfeaturequerydatatype_select' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_select', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeSelectService', true],
            'typegenerator_csfeaturequerydatatype_slider' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_slider', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeSliderService', true],
            'typegenerator_csfeaturequerydatatype_textarea' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_textarea', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeTextareaService', true],
            'typegenerator_csfeaturequerydatatype_time' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_time', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeTimeService', true],
            'typegenerator_csfeaturequerydatatype_wysiwyg' => ['privates', 'pimcore.datahub.graphql.csfeaturequerytypegenerator_datatype_wysiwyg', 'getPimcore_Datahub_Graphql_CsfeaturequerytypegeneratorDatatypeWysiwygService', true],
        ], [
            'typegenerator_csfeaturequerydatatype_booleanSelect' => '?',
            'typegenerator_csfeaturequerydatatype_calculatedValue' => '?',
            'typegenerator_csfeaturequerydatatype_checkbox' => '?',
            'typegenerator_csfeaturequerydatatype_country' => '?',
            'typegenerator_csfeaturequerydatatype_countrymultiselect' => '?',
            'typegenerator_csfeaturequerydatatype_date' => '?',
            'typegenerator_csfeaturequerydatatype_datetime' => '?',
            'typegenerator_csfeaturequerydatatype_input' => '?',
            'typegenerator_csfeaturequerydatatype_inputQuantityValue' => '?',
            'typegenerator_csfeaturequerydatatype_language' => '?',
            'typegenerator_csfeaturequerydatatype_languagemultiselect' => '?',
            'typegenerator_csfeaturequerydatatype_multiselect' => '?',
            'typegenerator_csfeaturequerydatatype_numeric' => '?',
            'typegenerator_csfeaturequerydatatype_quantityValue' => '?',
            'typegenerator_csfeaturequerydatatype_rgbaColor' => '?',
            'typegenerator_csfeaturequerydatatype_select' => '?',
            'typegenerator_csfeaturequerydatatype_slider' => '?',
            'typegenerator_csfeaturequerydatatype_textarea' => '?',
            'typegenerator_csfeaturequerydatatype_time' => '?',
            'typegenerator_csfeaturequerydatatype_wysiwyg' => '?',
        ]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'translation' => ['privates', 'pimcore.datahub.graphql.generaltype.factory.translation', 'getPimcore_Datahub_Graphql_Generaltype_Factory_TranslationService', true],
        ], [
            'translation' => '?',
        ]));

        $d = new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\VideoTypeDataType($instance);
        $e = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentElementType($instance);

        $f = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\PageType($instance, $e);
        $g = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\LinkType($instance);
        $h = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\EmailType($instance);
        $i = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\HardlinkType($instance, new \Pimcore\Bundle\DataHubBundle\GraphQL\General\AnyDocumentTargetType($instance));
        $j = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\SnippetType($instance, $e);

        $k = new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentType($instance, $f, $g, $h, $i, $j);
        $k->registerCustomDataType([]);
        $l = new \Pimcore\Bundle\DataHubBundle\GraphQL\ClassificationstoreType\Feature($instance);

        $instance->setSupportedGeneralTypes([]);
        $instance->setSupportedDataObjectQueryDataTypes([0 => 'booleanSelect', 1 => 'checkbox', 2 => 'newsletterActive', 3 => 'newsletterConfirmed', 4 => 'classificationstore', 5 => 'date', 6 => 'datetime', 7 => 'email', 8 => 'href', 9 => 'manyToOneRelation', 10 => 'fieldcollections', 11 => 'firstname', 12 => 'geobounds', 13 => 'geopolygon', 14 => 'geopoint', 15 => 'hotspotimage', 16 => 'image', 17 => 'imageGallery', 18 => 'link', 19 => 'externalImage', 20 => 'input', 21 => 'rgbaColor', 22 => 'time', 23 => 'calculatedValue', 24 => 'lastname', 25 => 'multihref', 26 => 'manyToManyRelation', 27 => 'manyToManyObjectRelation', 28 => 'reverseManyToManyObjectRelation', 29 => 'reverseObjectRelation', 30 => 'multihrefMetadata', 31 => 'advancedManyToManyRelation', 32 => 'advancedManyToManyObjectRelation', 33 => 'languagemultiselect', 34 => 'multiselect', 35 => 'countrymultiselect', 36 => 'numeric', 37 => 'quantityValue', 38 => 'inputQuantityValue', 39 => 'country', 40 => 'gender', 41 => 'language', 42 => 'select', 43 => 'slider', 44 => 'textarea', 45 => 'urlSlug', 46 => 'video', 47 => 'wysiwyg', 48 => 'table', 49 => 'structuredTable', 50 => 'block']);
        $instance->setSupportedDataObjectMutationDataTypes([0 => 'booleanSelect', 1 => 'checkbox', 2 => 'country', 3 => 'countrymultiselect', 4 => 'date', 5 => 'datetime', 6 => 'email', 7 => 'externalImage', 8 => 'fieldcollections', 9 => 'geopoint', 10 => 'firstname', 11 => 'gender', 12 => 'input', 13 => 'image', 14 => 'language', 15 => 'lastname', 16 => 'newsletterActive', 17 => 'manyToOneRelation', 18 => 'manyToManyRelation', 19 => 'manyToManyObjectRelation', 20 => 'advancedManyToManyRelation', 21 => 'advancedManyToManyObjectRelation', 22 => 'multiselect', 23 => 'newsletterConfirmed', 24 => 'numeric', 25 => 'select', 26 => 'slider', 27 => 'textarea', 28 => 'time', 29 => 'wysiwyg', 30 => 'quantityValue']);
        $instance->setSupportedDocumentElementQueryDataTypes([0 => 'areablock', 1 => 'block', 2 => 'checkbox', 3 => 'date', 4 => 'embed', 5 => 'input', 6 => 'image', 7 => 'link', 8 => 'multiselect', 9 => 'numeric', 10 => 'pdf', 11 => 'relation', 12 => 'relations', 13 => 'scheduledblock', 14 => 'select', 15 => 'table', 16 => 'textarea', 17 => 'wysiwyg', 18 => 'video']);
        $instance->setSupportedDocumentElementMutationDataTypes([0 => 'areablock', 1 => 'block', 2 => 'embed', 3 => 'image', 4 => 'input', 5 => 'multiselect', 6 => 'scheduledblock', 7 => 'select', 8 => 'wysiwyg']);
        $instance->setSupportedCsFeatureQueryDataTypes([0 => 'booleanSelect', 1 => 'calculatedValue', 2 => 'checkbox', 3 => 'country', 4 => 'countrymultiselect', 5 => 'date', 6 => 'datetime', 7 => 'input', 8 => 'inputQuantityValue', 9 => 'language', 10 => 'languagemultiselect', 11 => 'multiselect', 12 => 'numeric', 13 => 'rgbaColor', 14 => 'select', 15 => 'slider', 16 => 'textarea', 17 => 'time', 18 => 'quantityValue', 19 => 'wysiwyg']);
        $instance->registerAssetDataTypes(['asset_metadata_item' => new \Pimcore\Bundle\DataHubBundle\GraphQL\AssetType\AssetMetadataItem($instance), 'asset_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\AssetType\AssetInputType($instance), '_asset_folder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\AssetType\AssetFolderType($instance), 'asset_tree' => new \Pimcore\Bundle\DataHubBundle\GraphQL\AssetType\AssetTreeType($instance)]);
        $instance->registerTranslationDataTypes([]);
        $instance->registerDataObjectDataTypes(['elementdescriptor_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\ElementDescriptorInputType($instance), 'geopoint_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\GeopointInputType($instance), 'object_tree' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\ObjectTreeType($instance), '_object_folder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\ObjectFolderType($instance), 'object_datatype_hotspotimage' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\HotspotType($instance), 'manytoone' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\HrefType($instance), 'input_quantity_value' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\InputQuantityValueType($instance), 'quantity_value' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\QuantityValueType($instance), 'url_slug' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\UrlSlugType($instance), 'object_datatype_video' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\VideoType($instance, $d), 'object_datatype_video_data' => $d, 'quantity_value_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\QuantityValueInputType($instance), 'image_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\InputType\ImageInputType($instance)]);
        $instance->registerDocumentDataTypes(['document' => $k, 'document_tree' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentTreeType($instance), 'document_element' => $e, 'document_email' => $h, 'document_hardlink' => $i, 'document_link' => $g, 'document_page' => $f, 'document_snippet' => $j, '_document_folder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentFolderType($instance), 'document_link_input' => new \Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentLinkInputType($instance)]);
        $instance->registerClassificationStoreDataTypes(['cs_group' => new \Pimcore\Bundle\DataHubBundle\GraphQL\ClassificationstoreType\Group($instance, $l), 'cs_feature' => $l]);
        $instance->registerPropertyDataTypes(['elementproperty' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\ElementPropertyType($instance), 'hotspotmetadata' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\HotspotMetadataType($instance), 'property_asset' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\AssetType($instance), 'property_document' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\DocumentType($instance), 'property_assetfolder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\AssetFolderType($instance), 'property_documentfolder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\DocumentFolderType($instance), 'property_objectfolder' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\ObjectFolderType($instance), 'property_object' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\DataObjectType($instance, new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\ObjectsType($instance)), 'property_checkbox' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\CheckboxType($instance), 'property_textarea' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\TextareaType($instance), 'property_text' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\TextType($instance), 'property_select' => new \Pimcore\Bundle\DataHubBundle\GraphQL\PropertyType\SelectType($instance)]);

        $c->setGraphQlService($instance);

        $b->setGraphQlService($instance);

        $a->setGraphQlService($instance);

        return $instance;
    }
}
