<?php

namespace ContainerY9hqK1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUrlGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Sitemap\UrlGenerator' shared autowired service.
     *
     * @return \Pimcore\Sitemap\UrlGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/UrlGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/UrlGenerator.php';

        return $container->privates['Pimcore\\Sitemap\\UrlGenerator'] = new \Pimcore\Sitemap\UrlGenerator(($container->services['pimcore.routing.router.request_context'] ?? $container->getPimcore_Routing_Router_RequestContextService()));
    }
}
