<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GD2jBRfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GD2jBRf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GD2jBRf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'oAuthHandler' => ['privates', 'CustomerManagementFrameworkBundle\\Security\\OAuth\\OAuthRegistrationHandler', 'getOAuthRegistrationHandlerService', true],
            'user' => ['privates', '.errored..service_locator.GD2jBRf.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.GD2jBRf": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'oAuthHandler' => 'CustomerManagementFrameworkBundle\\Security\\OAuth\\OAuthRegistrationHandler',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
