<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9HBPZnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9HB_PZn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9HB_PZn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'breadcrumbHelperService' => ['privates', 'App\\Website\\Navigation\\BreadcrumbHelperService', 'getBreadcrumbHelperServiceService', true],
            'headTitleHelper' => ['privates', 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle', 'getHeadTitleService', false],
            'newsLinkGenerator' => ['services', 'App\\Website\\LinkGenerator\\NewsLinkGenerator', 'getNewsLinkGeneratorService', false],
            'placeholderHelper' => ['privates', 'Pimcore\\Twig\\Extension\\Templating\\Placeholder', 'getPlaceholderService', false],
        ], [
            'breadcrumbHelperService' => 'App\\Website\\Navigation\\BreadcrumbHelperService',
            'headTitleHelper' => 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle',
            'newsLinkGenerator' => 'App\\Website\\LinkGenerator\\NewsLinkGenerator',
            'placeholderHelper' => 'Pimcore\\Twig\\Extension\\Templating\\Placeholder',
        ]);
    }
}
