<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SoX7gOHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SoX7gOH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SoX7gOH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'breadcrumbHelperService' => ['privates', 'App\\Website\\Navigation\\BreadcrumbHelperService', 'getBreadcrumbHelperServiceService', true],
            'ecommerceFactory' => ['services', 'pimcore_ecommerce.factory', 'getPimcoreEcommerce_FactoryService', true],
            'headTitleHelper' => ['privates', 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle', 'getHeadTitleService', false],
            'product' => ['privates', '.errored..service_locator.SoX7gOH.Pimcore\\Model\\DataObject\\Concrete', NULL, 'Cannot autowire service ".service_locator.SoX7gOH": it references class "Pimcore\\Model\\DataObject\\Concrete" but no such service exists.'],
            'productLinkGenerator' => ['services', 'App\\Website\\LinkGenerator\\ProductLinkGenerator', 'getProductLinkGeneratorService', false],
            'segmentTrackingHelperService' => ['privates', 'App\\Services\\SegmentTrackingHelperService', 'getSegmentTrackingHelperServiceService', true],
        ], [
            'breadcrumbHelperService' => 'App\\Website\\Navigation\\BreadcrumbHelperService',
            'ecommerceFactory' => '?',
            'headTitleHelper' => 'Pimcore\\Twig\\Extension\\Templating\\HeadTitle',
            'product' => 'Pimcore\\Model\\DataObject\\Concrete',
            'productLinkGenerator' => 'App\\Website\\LinkGenerator\\ProductLinkGenerator',
            'segmentTrackingHelperService' => 'App\\Services\\SegmentTrackingHelperService',
        ]);
    }
}
