<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KGxsxAFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KGxsxAF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KGxsxAF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['services', 'GuzzleHttp\\Client', 'getClientService', true],
            'formatter' => ['services', 'Pimcore\\Localization\\IntlFormatter', 'getIntlFormatterService', false],
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', false],
        ], [
            'client' => '?',
            'formatter' => 'Pimcore\\Localization\\IntlFormatter',
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
        ]);
    }
}
