<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAreabrickManagerInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Extension\Document\Areabrick\AreabrickManagerInterface' shared autowired service.
     *
     * @return \Pimcore\Extension\Document\Areabrick\AreabrickManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Extension/Document/Areabrick/AreabrickManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Extension/Document/Areabrick/AreabrickManager.php';

        $container->services['Pimcore\\Extension\\Document\\Areabrick\\AreabrickManagerInterface'] = $instance = new \Pimcore\Extension\Document\Areabrick\AreabrickManager(($container->services['Pimcore\\Extension\\Config'] ?? $container->get('Pimcore\\Extension\\Config', 1)), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blockquote' => ['privates', 'app.area.brick.blockquote', 'getApp_Area_Brick_BlockquoteService', true],
            'email-image' => ['privates', 'app.area.brick.email_image', 'getApp_Area_Brick_EmailImageService', true],
            'email-news' => ['privates', 'app.area.brick.email_news', 'getApp_Area_Brick_EmailNewsService', true],
            'email-teaser' => ['privates', 'app.area.brick.email_teaser', 'getApp_Area_Brick_EmailTeaserService', true],
            'email-wysiwyg' => ['privates', 'app.area.brick.email_wysiwyg', 'getApp_Area_Brick_EmailWysiwygService', true],
            'embed' => ['privates', 'app.area.brick.embed', 'getApp_Area_Brick_EmbedService', true],
            'featurette' => ['privates', 'app.area.brick.featurette', 'getApp_Area_Brick_FeaturetteService', true],
            'gallery-carousel' => ['privates', 'app.area.brick.gallery_carousel', 'getApp_Area_Brick_GalleryCarouselService', true],
            'gallery-folder' => ['privates', 'app.area.brick.gallery_folder', 'getApp_Area_Brick_GalleryFolderService', true],
            'gallery-single-images' => ['privates', 'app.area.brick.gallery_single_images', 'getApp_Area_Brick_GallerySingleImagesService', true],
            'headlines' => ['privates', 'app.area.brick.headlines', 'getApp_Area_Brick_HeadlinesService', true],
            'hero-grid' => ['privates', 'app.area.brick.hero_grid', 'getApp_Area_Brick_HeroGridService', true],
            'hero-teaser' => ['privates', 'app.area.brick.hero_teaser', 'getApp_Area_Brick_HeroTeaserService', true],
            'horizontal-line' => ['privates', 'app.area.brick.horizontal_line', 'getApp_Area_Brick_HorizontalLineService', true],
            'icon-teaser-row' => ['privates', 'app.area.brick.icon_teaser_row', 'getApp_Area_Brick_IconTeaserRowService', true],
            'image' => ['privates', 'app.area.brick.image', 'getApp_Area_Brick_ImageService', true],
            'image-hotspot-marker' => ['privates', 'app.area.brick.image_hotspot_marker', 'getApp_Area_Brick_ImageHotspotMarkerService', true],
            'image-metadata' => ['privates', 'app.area.brick.image_metadata', 'getApp_Area_Brick_ImageMetadataService', true],
            'pdf' => ['privates', 'app.area.brick.pdf', 'getApp_Area_Brick_PdfService', true],
            'personalized-product-teaser' => ['privates', 'app.area.brick.personalized_product_teaser', 'getApp_Area_Brick_PersonalizedProductTeaserService', true],
            'print-key-visual' => ['privates', 'app.area.brick.print_key_visual', 'getApp_Area_Brick_PrintKeyVisualService', true],
            'print-page-break' => ['privates', 'app.area.brick.print_page_break', 'getApp_Area_Brick_PrintPageBreakService', true],
            'print-product-row' => ['privates', 'app.area.brick.print_product_row', 'getApp_Area_Brick_PrintProductRowService', true],
            'print-product-table' => ['privates', 'app.area.brick.print_product_table', 'getApp_Area_Brick_PrintProductTableService', true],
            'print-title-page' => ['privates', 'app.area.brick.print_title_page', 'getApp_Area_Brick_PrintTitlePageService', true],
            'print-toc' => ['privates', 'app.area.brick.print_toc', 'getApp_Area_Brick_PrintTocService', true],
            'print-wysiwyg' => ['privates', 'app.area.brick.print_wysiwyg', 'getApp_Area_Brick_PrintWysiwygService', true],
            'product-grid' => ['privates', 'app.area.brick.product_grid', 'getApp_Area_Brick_ProductGridService', true],
            'product-teaser' => ['privates', 'app.area.brick.product_teaser', 'getApp_Area_Brick_ProductTeaserService', true],
            'standard-teaser' => ['privates', 'app.area.brick.standard_teaser', 'getApp_Area_Brick_StandardTeaserService', true],
            'text-accordion' => ['privates', 'app.area.brick.text_accordion', 'getApp_Area_Brick_TextAccordionService', true],
            'time-slider-featurette' => ['privates', 'app.area.brick.time_slider_featurette', 'getApp_Area_Brick_TimeSliderFeaturetteService', true],
            'video' => ['privates', 'app.area.brick.video', 'getApp_Area_Brick_VideoService', true],
            'wysiwyg' => ['privates', 'app.area.brick.wysiwyg', 'getApp_Area_Brick_WysiwygService', true],
            'wysiwyg-with-images' => ['privates', 'app.area.brick.wysiwyg_with_images', 'getApp_Area_Brick_WysiwygWithImagesService', true],
        ], [
            'blockquote' => '?',
            'email-image' => '?',
            'email-news' => '?',
            'email-teaser' => '?',
            'email-wysiwyg' => '?',
            'embed' => '?',
            'featurette' => '?',
            'gallery-carousel' => '?',
            'gallery-folder' => '?',
            'gallery-single-images' => '?',
            'headlines' => '?',
            'hero-grid' => '?',
            'hero-teaser' => '?',
            'horizontal-line' => '?',
            'icon-teaser-row' => '?',
            'image' => '?',
            'image-hotspot-marker' => '?',
            'image-metadata' => '?',
            'pdf' => '?',
            'personalized-product-teaser' => '?',
            'print-key-visual' => '?',
            'print-page-break' => '?',
            'print-product-row' => '?',
            'print-product-table' => '?',
            'print-title-page' => '?',
            'print-toc' => '?',
            'print-wysiwyg' => '?',
            'product-grid' => '?',
            'product-teaser' => '?',
            'standard-teaser' => '?',
            'text-accordion' => '?',
            'time-slider-featurette' => '?',
            'video' => '?',
            'wysiwyg' => '?',
            'wysiwyg-with-images' => '?',
        ]));

        $instance->registerService('print-product-row', 'app.area.brick.print_product_row');
        $instance->registerService('print-page-break', 'app.area.brick.print_page_break');
        $instance->registerService('image-hotspot-marker', 'app.area.brick.image_hotspot_marker');
        $instance->registerService('image-metadata', 'app.area.brick.image_metadata');
        $instance->registerService('wysiwyg-with-images', 'app.area.brick.wysiwyg_with_images');
        $instance->registerService('time-slider-featurette', 'app.area.brick.time_slider_featurette');
        $instance->registerService('print-key-visual', 'app.area.brick.print_key_visual');
        $instance->registerService('image', 'app.area.brick.image');
        $instance->registerService('email-teaser', 'app.area.brick.email_teaser');
        $instance->registerService('headlines', 'app.area.brick.headlines');
        $instance->registerService('product-teaser', 'app.area.brick.product_teaser');
        $instance->registerService('print-title-page', 'app.area.brick.print_title_page');
        $instance->registerService('horizontal-line', 'app.area.brick.horizontal_line');
        $instance->registerService('gallery-folder', 'app.area.brick.gallery_folder');
        $instance->registerService('email-news', 'app.area.brick.email_news');
        $instance->registerService('print-product-table', 'app.area.brick.print_product_table');
        $instance->registerService('product-grid', 'app.area.brick.product_grid');
        $instance->registerService('email-wysiwyg', 'app.area.brick.email_wysiwyg');
        $instance->registerService('email-image', 'app.area.brick.email_image');
        $instance->registerService('text-accordion', 'app.area.brick.text_accordion');
        $instance->registerService('standard-teaser', 'app.area.brick.standard_teaser');
        $instance->registerService('gallery-single-images', 'app.area.brick.gallery_single_images');
        $instance->registerService('icon-teaser-row', 'app.area.brick.icon_teaser_row');
        $instance->registerService('print-toc', 'app.area.brick.print_toc');
        $instance->registerService('featurette', 'app.area.brick.featurette');
        $instance->registerService('hero-grid', 'app.area.brick.hero_grid');
        $instance->registerService('pdf', 'app.area.brick.pdf');
        $instance->registerService('gallery-carousel', 'app.area.brick.gallery_carousel');
        $instance->registerService('personalized-product-teaser', 'app.area.brick.personalized_product_teaser');
        $instance->registerService('hero-teaser', 'app.area.brick.hero_teaser');
        $instance->registerService('wysiwyg', 'app.area.brick.wysiwyg');
        $instance->registerService('embed', 'app.area.brick.embed');
        $instance->registerService('blockquote', 'app.area.brick.blockquote');
        $instance->registerService('print-wysiwyg', 'app.area.brick.print_wysiwyg');
        $instance->registerService('video', 'app.area.brick.video');

        return $instance;
    }
}
