<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionTriggerQueueCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.CustomerManagementFrameworkBundle\Command\ActionTriggerQueueCommand' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Command\ActionTriggerQueueCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Command/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LockableTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Command/ActionTriggerQueueCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActionTrigger/Queue/QueueInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActionTrigger/Queue/DefaultQueue.php';

        $container->services['console.command.public_alias.CustomerManagementFrameworkBundle\\Command\\ActionTriggerQueueCommand'] = $instance = new \CustomerManagementFrameworkBundle\Command\ActionTriggerQueueCommand();

        $instance->setLogger(($container->services['monolog.logger.cmf'] ?? $container->load('getMonolog_Logger_CmfService')));
        $instance->setActionTriggerQueue(($container->services['CustomerManagementFrameworkBundle\\ActionTrigger\\Queue\\QueueInterface'] ?? ($container->services['CustomerManagementFrameworkBundle\\ActionTrigger\\Queue\\QueueInterface'] = new \CustomerManagementFrameworkBundle\ActionTrigger\Queue\DefaultQueue())));

        return $instance;
    }
}
