<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailabilitySystemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/AvailabilitySystem/AvailabilitySystemInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/AvailabilitySystem/AvailabilitySystem.php';

        return $container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\AvailabilitySystem\\AvailabilitySystem'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem();
    }
}
