<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_CustomReport_Adapter_TermSegmentBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.custom_report.adapter.term_segment_builder' shared autowired service.
     *
     * @return \Pimcore\Model\Tool\CustomReport\Adapter\DefaultCustomReportAdapterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/Tool/CustomReport/Adapter/CustomReportAdapterFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/Tool/CustomReport/Adapter/DefaultCustomReportAdapterFactory.php';

        return $container->services['cmf.custom_report.adapter.term_segment_builder'] = new \Pimcore\Model\Tool\CustomReport\Adapter\DefaultCustomReportAdapterFactory('CustomerManagementFrameworkBundle\\CustomReport\\Adapter\\TermSegmentBuilder');
    }
}
