<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerDuplicatesServiceInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\CustomerDuplicatesService\CustomerDuplicatesServiceInterface' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\CustomerDuplicatesService\DefaultCustomerDuplicatesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/CustomerDuplicatesService/CustomerDuplicatesServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/CustomerDuplicatesService/DefaultCustomerDuplicatesService.php';

        return $container->services['CustomerManagementFrameworkBundle\\CustomerDuplicatesService\\CustomerDuplicatesServiceInterface'] = new \CustomerManagementFrameworkBundle\CustomerDuplicatesService\DefaultCustomerDuplicatesService($container->parameters['pimcore_customer_management_framework.customer_duplicates_services.duplicateCheckFields'], []);
    }
}
