<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConcreteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SoX7gOH.Pimcore\Model\DataObject\Concrete' shared service.
     *
     * @return \Pimcore\Model\DataObject\Concrete
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SoX7gOH": it references class "Pimcore\\Model\\DataObject\\Concrete" but no such service exists.');
    }
}
