<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_ActivityViewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.activity_view' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\ActivityView\DefaultActivityView
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActivityView/ActivityViewInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActivityView/DefaultActivityView.php';

        return $container->services['cmf.activity_view'] = new \CustomerManagementFrameworkBundle\ActivityView\DefaultActivityView(($container->services['cmf.view_formatter'] ?? $container->getCmf_ViewFormatterService()));
    }
}
