<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterDefinitionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\Controller\Admin\Customers\FilterDefinitionController' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Controller\Admin\Customers\FilterDefinitionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/DoubleAuthenticationControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/KernelControllerEventInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin/Customers/FilterDefinitionController.php';

        $container->services['CustomerManagementFrameworkBundle\\Controller\\Admin\\Customers\\FilterDefinitionController'] = $instance = new \CustomerManagementFrameworkBundle\Controller\Admin\Customers\FilterDefinitionController(($container->services['CustomerManagementFrameworkBundle\\Helper\\JsConfigService'] ?? ($container->services['CustomerManagementFrameworkBundle\\Helper\\JsConfigService'] = new \CustomerManagementFrameworkBundle\Helper\JsConfigService())), ($container->services['Knp\\Component\\Pager\\PaginatorInterface'] ?? $container->getPaginatorInterfaceService()));

        $instance->setContainer(($container->privates['.service_locator.oafe0zm'] ?? $container->load('get_ServiceLocator_Oafe0zmService'))->withContext('CustomerManagementFrameworkBundle\\Controller\\Admin\\Customers\\FilterDefinitionController', $container));

        return $instance;
    }
}
