<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_GoogleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hwi_oauth.resource_owner.google' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GoogleResourceOwner.php';

        return $container->services['hwi_oauth.resource_owner.google'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner(($container->privates['hwi_oauth.http_client'] ?? $container->load('getHwiOauth_HttpClientService')), ($container->privates['security.http_utils'] ?? $container->getSecurity_HttpUtilsService()), ['client_id' => '<google_client_id>', 'client_secret' => '<google_client_secret>', 'scope' => 'openid email profile', 'options' => ['csrf' => true], 'paths' => []], 'google', ($container->privates['hwi_oauth.storage.session'] ?? $container->load('getHwiOauth_Storage_SessionService')));
    }
}
