<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexUpdateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexUpdateService' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexUpdateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/IndexService/IndexUpdateService.php';

        return $container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\IndexService\\IndexUpdateService'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexUpdateService(($container->services['pimcore_ecommerce.index_service'] ?? $container->load('getPimcoreEcommerce_IndexServiceService')));
    }
}
