<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\ListHelper' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\ListHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/ListHelper.php';

        return $container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\FilterService\\ListHelper'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\ListHelper();
    }
}
