<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_VoucherServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore_ecommerce.voucher_service' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\DefaultService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/VoucherServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php';

        return $container->services['pimcore_ecommerce.voucher_service'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\DefaultService(($container->services['Pimcore\\Localization\\LocaleServiceInterface'] ?? $container->getLocaleServiceInterfaceService()), $container->parameters['pimcore_ecommerce.voucher_service.options']);
    }
}
