<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Sitemaps\ProductGenerator' shared autowired service.
     *
     * @return \App\Sitemaps\ProductGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Sitemap/Element/AbstractElementGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Sitemaps/ProductGenerator.php';

        return $container->privates['App\\Sitemaps\\ProductGenerator'] = new \App\Sitemaps\ProductGenerator([], [0 => ($container->privates['App\\Sitemaps\\Processors\\AbsoluteURLProcessor'] ?? $container->load('getAbsoluteURLProcessorService'))]);
    }
}
