<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_FactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore_ecommerce.factory' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/TenantAwareServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/CheckoutTenantAwareServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartManagerLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CartManager/CartManagerLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/NameServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/PriceSystem/PriceSystemLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/PriceSystem/PriceSystemLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/AvailabilitySystem/AvailabilitySystemLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/AvailabilitySystem/AvailabilitySystemLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactoryLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactoryLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/DependencyInjection/ServiceLocator/AssortmentTenantAwareServiceLocator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterServiceLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/FilterService/FilterServiceLocator.php';

        $a = ($container->services['pimcore_ecommerce.environment'] ?? $container->getPimcoreEcommerce_EnvironmentService());
        $b = ($container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\OrderManager\\OrderManagerLocatorInterface'] ?? $container->load('getOrderManagerLocatorInterfaceService'));

        if (isset($container->services['pimcore_ecommerce.factory'])) {
            return $container->services['pimcore_ecommerce.factory'];
        }
        $c = ($container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\CheckoutManager\\CommitOrderProcessorLocatorInterface'] ?? $container->load('getCommitOrderProcessorLocatorInterfaceService'));

        if (isset($container->services['pimcore_ecommerce.factory'])) {
            return $container->services['pimcore_ecommerce.factory'];
        }

        return $container->services['pimcore_ecommerce.factory'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\Factory($container, new \Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartManagerLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['services', 'pimcore_ecommerce.cart_manager.default', 'getPimcoreEcommerce_CartManager_DefaultService', true],
        ], [
            'default' => '?',
        ]), $a, false), $b, ($container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\PricingManager\\PricingManagerLocatorInterface'] ?? $container->load('getPricingManagerLocatorInterfaceService')), new \Pimcore\Bundle\EcommerceFrameworkBundle\PriceSystem\PriceSystemLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['privates', 'app.default_price_system', 'getApp_DefaultPriceSystemService', true],
        ], [
            'default' => '?',
        ])), new \Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystemLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['privates', 'Pimcore\\Bundle\\EcommerceFrameworkBundle\\AvailabilitySystem\\AvailabilitySystem', 'getAvailabilitySystemService', true],
        ], [
            'default' => '?',
        ])), new \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CheckoutManagerFactoryLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['privates', 'pimcore_ecommerce.checkout_manager.default.factory', 'getPimcoreEcommerce_CheckoutManager_Default_FactoryService', true],
        ], [
            'default' => '?',
        ]), $a, false), $c, new \Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterServiceLocator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'default' => ['privates', 'pimcore_ecommerce.filter_service.default', 'getPimcoreEcommerce_FilterService_DefaultService', true],
        ], [
            'default' => '?',
        ]), $a, false));
    }
}
