<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueueBuilderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CustomerManagementFrameworkBundle\SegmentAssignment\QueueBuilder\QueueBuilderInterface' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\SegmentAssignment\QueueBuilder\DefaultQueueBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/SegmentAssignment/QueueBuilder/QueueBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/SegmentAssignment/QueueBuilder/DefaultQueueBuilder.php';

        return $container->services['CustomerManagementFrameworkBundle\\SegmentAssignment\\QueueBuilder\\QueueBuilderInterface'] = new \CustomerManagementFrameworkBundle\SegmentAssignment\QueueBuilder\DefaultQueueBuilder('plugin_cmf_segment_assignment_queue', ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
