<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetQueueCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ResetQueueCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ResetQueueCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Command/IndexService/AbstractIndexServiceCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/Command/IndexService/ResetQueueCommand.php';

        return $container->services['console.command.public_alias.Pimcore\\Bundle\\EcommerceFrameworkBundle\\Command\\IndexService\\ResetQueueCommand'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\Command\IndexService\ResetQueueCommand();
    }
}
