<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStateMachine_SimpleAssetWorkflowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'state_machine.simple_asset_workflow' shared autowired service.
     *
     * @return \Symfony\Component\Workflow\StateMachine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/StateMachine.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Definition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/NotesAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notification/NotificationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/NotesAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notification/NotificationTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/MarkingStore/StateTableMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['state_machine.simple_asset_workflow'])) {
            return $container->services['state_machine.simple_asset_workflow'];
        }

        return $container->services['state_machine.simple_asset_workflow'] = new \Symfony\Component\Workflow\StateMachine(new \Symfony\Component\Workflow\Definition([0 => 'start', 1 => 'review_license', 2 => 'finished'], [0 => new \Pimcore\Workflow\Transition('start_workflow', 'start', 'review_license', ['label' => 'Start Workflow', 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change']), 1 => new \Pimcore\Workflow\Transition('finish_review', 'review_license', 'finished', ['label' => 'Finish Review', 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change']), 2 => new \Pimcore\Workflow\Transition('restart_review', 'finished', 'review_license', ['label' => 'Restart Review', 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change'])], [0 => 'start']), new \Pimcore\Workflow\MarkingStore\StateTableMarkingStore('simple_asset_workflow'), $a, 'simple_asset_workflow', NULL);
    }
}
