<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentTrackingHelperServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\SegmentTrackingHelperService' shared autowired service.
     *
     * @return \App\Services\SegmentTrackingHelperService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/SegmentTrackingHelperService.php';

        $a = ($container->privates['CustomerManagementFrameworkBundle\\Targeting\\SegmentTracker'] ?? $container->load('getSegmentTrackerService'));

        if (isset($container->privates['App\\Services\\SegmentTrackingHelperService'])) {
            return $container->privates['App\\Services\\SegmentTrackingHelperService'];
        }

        return $container->privates['App\\Services\\SegmentTrackingHelperService'] = new \App\Services\SegmentTrackingHelperService(($container->privates['Pimcore\\Targeting\\VisitorInfoStorage'] ?? ($container->privates['Pimcore\\Targeting\\VisitorInfoStorage'] = new \Pimcore\Targeting\VisitorInfoStorage())), $a, ($container->privates['App\\Ecommerce\\IndexService\\SegmentGetter'] ?? $container->getSegmentGetterService()), ($container->services['CustomerManagementFrameworkBundle\\SegmentManager\\SegmentManagerInterface'] ?? $container->getSegmentManagerInterfaceService()));
    }
}
