<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackingCodeSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Analytics\GoogleTagManager\EventSubscriber\TrackingCodeSubscriber' shared autowired service.
     *
     * @return \Pimcore\Analytics\GoogleTagManager\EventSubscriber\TrackingCodeSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Analytics/GoogleTagManager/EventSubscriber/TrackingCodeSubscriber.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['Pimcore\\Analytics\\GoogleTagManager\\EventSubscriber\\TrackingCodeSubscriber'])) {
            return $container->privates['Pimcore\\Analytics\\GoogleTagManager\\EventSubscriber\\TrackingCodeSubscriber'];
        }

        $container->privates['Pimcore\\Analytics\\GoogleTagManager\\EventSubscriber\\TrackingCodeSubscriber'] = $instance = new \Pimcore\Analytics\GoogleTagManager\EventSubscriber\TrackingCodeSubscriber(($container->services['pimcore_ecommerce.tracking.tracking_manager'] ?? $container->getPimcoreEcommerce_Tracking_TrackingManagerService()), $a);

        $instance->setResponseHelper(($container->services['Pimcore\\Http\\ResponseHelper'] ?? ($container->services['Pimcore\\Http\\ResponseHelper'] = new \Pimcore\Http\ResponseHelper())));
        $instance->setPimcoreContextResolver(($container->services['Pimcore\\Http\\Request\\Resolver\\PimcoreContextResolver'] ?? $container->getPimcoreContextResolverService()));

        return $instance;
    }
}
