<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nSkPvFx.CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter' shared service.
     *
     * @return \CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nSkPvFx": it references class "CustomerManagementFrameworkBundle\\Newsletter\\ProviderHandler\\Mailchimp\\TemplateExporter" but no such service exists.');
    }
}
