<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUrlSlugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nHbyZrv.Pimcore\Model\DataObject\Data\UrlSlug' shared service.
     *
     * @return \Pimcore\Model\DataObject\Data\UrlSlug
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nHbyZrv": it references class "Pimcore\\Model\\DataObject\\Data\\UrlSlug" but no such service exists.');
    }
}
