<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_ProductDataEnrichmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'workflow.product_data_enrichment' shared autowired service.
     *
     * @return \Symfony\Component\Workflow\Workflow
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Definition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/NotesAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notification/NotificationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/NotesAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notification/NotificationTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/CustomHtmlServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/Notes/AbstractCustomHtmlService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/Workflow/CustomHtmlService.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/MarkingStore/StateTableMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['workflow.product_data_enrichment'])) {
            return $container->services['workflow.product_data_enrichment'];
        }
        $b = new \Pimcore\Workflow\Transition('start_work', [0 => 'todo'], [0 => 'edit_text', 1 => 'edit_images'], ['label' => 'Start Work', 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change']);
        $b->setCustomHtmlService(new \App\Services\Workflow\CustomHtmlService('mark_done_all', false, 'top'));
        $c = new \Pimcore\Workflow\Transition('mark_text_done', [0 => 'edit_text'], [0 => 'done_text'], ['label' => 'Mark Text Done', 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change']);
        $c->setCustomHtmlService(new \App\Services\Workflow\CustomHtmlService('mark_done_all', false, 'top'));
        $d = new \Pimcore\Workflow\Transition('mark_images_done', [0 => 'edit_images'], [0 => 'done_images'], ['label' => 'Mark Images Done', 'notificationSettings' => [0 => ['notifyUsers' => [0 => 'admin'], 'notifyRoles' => [0 => 'projectmanagers', 1 => 'admins'], 'channelType' => [0 => 'mail', 1 => 'pimcore_notification'], 'mailType' => 'template', 'mailPath' => '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig']], 'objectLayout' => false, 'changePublishedState' => 'no_change']);
        $d->setCustomHtmlService(new \App\Services\Workflow\CustomHtmlService('mark_done_all', false, 'top'));
        $e = new \Pimcore\Workflow\Transition('mark_done_all', [0 => 'done_text', 1 => 'done_images'], [0 => 'done_all'], ['label' => 'Mark Product Done', 'changePublishedState' => 'force_published', 'notes' => ['commentEnabled' => true, 'customHtml' => ['service' => 'App\\Services\\Workflow\\CustomHtmlService', 'position' => 'top'], 'commentRequired' => false, 'type' => 'Status update', 'additionalFields' => []], 'notificationSettings' => [0 => ['notifyUsers' => [0 => 'admin'], 'notifyRoles' => [0 => 'projectmanagers', 1 => 'admins'], 'channelType' => [0 => 'mail', 1 => 'pimcore_notification'], 'mailType' => 'template', 'mailPath' => '@PimcoreCore/Workflow/NotificationEmail/notificationEmail.html.twig']], 'objectLayout' => false]);
        $e->setCustomHtmlService(new \App\Services\Workflow\CustomHtmlService('mark_done_all', false, 'top'));

        return $container->services['workflow.product_data_enrichment'] = new \Symfony\Component\Workflow\Workflow(new \Symfony\Component\Workflow\Definition([0 => 'todo', 1 => 'edit_text', 2 => 'edit_images', 3 => 'done_text', 4 => 'done_images', 5 => 'done_all'], [0 => $b, 1 => $c, 2 => $d, 3 => $e, 4 => new \Pimcore\Workflow\Transition('reopen_issue', [0 => 'done_all'], [0 => 'todo'], ['label' => 'Reopen Product', 'notes' => ['commentEnabled' => true, 'commentRequired' => true, 'type' => 'Status update', 'additionalFields' => []], 'objectLayout' => false, 'notificationSettings' => [], 'changePublishedState' => 'no_change'])], [0 => 'todo']), new \Pimcore\Workflow\MarkingStore\StateTableMarkingStore('product_data_enrichment'), $a, 'product_data_enrichment', NULL);
    }
}
