<?php

namespace ContainerBPqIAxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'workflow.registry' shared autowired service.
     *
     * @return \Symfony\Component\Workflow\Registry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Registry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/SupportStrategy/WorkflowSupportStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php';
        include_once \dirname(__DIR__, 4).'/src/Workflow/SupportsStrategy.php';

        $container->privates['workflow.registry'] = $instance = new \Symfony\Component\Workflow\Registry();

        $instance->addWorkflow(($container->services['state_machine.simple_asset_workflow'] ?? $container->load('getStateMachine_SimpleAssetWorkflowService')), new \Pimcore\Workflow\SupportStrategy\ExpressionSupportStrategy(($container->services['Pimcore\\Workflow\\ExpressionService'] ?? $container->load('getExpressionServiceService')), '\\Pimcore\\Model\\Asset', 'is_fully_authenticated()'));
        $instance->addWorkflow(($container->services['workflow.product_data_enrichment'] ?? $container->load('getWorkflow_ProductDataEnrichmentService')), new \App\Workflow\SupportsStrategy());

        return $instance;
    }
}
